Update Jenkinfile

diff --git a/Jenkinfile b/Jenkinfile
--- a/Jenkinfile
+++ b/Jenkinfile
@@ -19,14 +19,15 @@ pipeline {
 
         stage('Build Docker Image') {
             steps {
-                    // Build the Docker image
-                    
-                    dir('.') {
-                       sh 'echo "Running in $(pwd)"'
-                       sh 'echo start build the Docker image = $DOCKER_IMAGE'
-                       sh 'docker build -t $DOCKER_IMAGE .'
-                    }   
-                  
+                dir('03_Jenkins/week13/03_Github_webhook') {  // Adjust this path
+                    sh '''
+                    if [ ! -f Dockerfile ]; then
+                        echo "Dockerfile not found!"
+                        exit 1
+                    fi
+                    docker build -t earth123456789/fastapi-webhook:latest .
+                    '''
+                }
             }
         }
 
